
//set namespace
	export const NAME = 'profile'

//add actions
	export const SUBMIT_IS_LOADING = `${NAME}/SUBMIT_IS_LOADING`;
	export const SUBMIT_HAS_ERRORED = `${NAME}/SUBMIT_HAS_ERRORED`;
	export const SUBMIT_NAME_UPDATE_SUCCESS = `${NAME}/SUBMIT_NAME_UPDATE_SUCCESS`;
	export const SUBMIT_PROFILE_PICTURE_SUCCESS = `${NAME}/SUBMIT_PROFILE_PICTURE_SUCCESS`;

	export const IMAGE_PICKER_SUCCESS = `${NAME}/IMAGE_PICKER_SUCCESS`;

	export const FETCH_IS_LOADING = `${NAME}/FETCH_IS_LOADING`;
	export const FETCH_HAS_ERRORED = `${NAME}/FETCH_HAS_ERRORED`;
	export const FETCH_NAME_SUCCESS = `${NAME}/FETCH_NAME_SUCCESS`;
	export const FETCH_PROFILE_PICTURE_SUCCESS = `${NAME}/FETCH_PROFILE_PICTURE_SUCCESS`;
